export const defaultDockAwb = {
    id: 0,
    s_mawb: '',
    s_hawb: '',
    s_unit: '',
    s_type: '',
    s_status: '',
    s_state: '',
    s_trucking_company: '',
    s_trucking_driver: '',
    s_transaction_id: '',
    s_mawb_id: '',
    t_kiosk_submitted: '',
    t_counter_end: '',
    t_dock_ownership: '',
    s_counter_ownership_agent: '',
    s_dock_ownership: '',
    s_driver_photo_link: '',
    b_trucking_sms: false,
    t_created: '',
    s_created_by: '',
    s_location: '',
    s_notes: '',
    s_dock_door: '',
    s_dock_door_assigned: '',
    s_dock_door_guid: '',
    t_dock_door: ''
}

export const defaultCompany = {
    s_transaction_id: '',
    exportCount: 0,
    importCount: 0,
    s_trucking_company: '',
    s_trucking_driver: '',
    s_dock_ownership: '',
    s_dock_door: '',
    s_status: '',
    s_state: '',
    waitTime: '',
    processingTime: '',
    overDue: false,
    awbs: []
}